//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.nib` struct is generated, and contains static references to 2 nibs.
  struct nib {
    /// Nib `AddressViewCell`.
    static let addressViewCell = _R.nib._AddressViewCell()
    /// Nib `ItemViewCell`.
    static let itemViewCell = _R.nib._ItemViewCell()
    
    /// `UINib(name: "AddressViewCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.addressViewCell) instead")
    static func addressViewCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.addressViewCell)
    }
    
    /// `UINib(name: "ItemViewCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.itemViewCell) instead")
    static func itemViewCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.itemViewCell)
    }
    
    static func addressViewCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> AddressViewCell? {
      return R.nib.addressViewCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? AddressViewCell
    }
    
    static func itemViewCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> ItemViewCell? {
      return R.nib.itemViewCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? ItemViewCell
    }
    
    fileprivate init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 1 reuse identifiers.
  struct reuseIdentifier {
    /// Reuse identifier `CELL`.
    static let celL: Rswift.ReuseIdentifier<UIKit.UITableViewCell> = Rswift.ReuseIdentifier(identifier: "CELL")
    
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 2 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `Main`.
    static let main = _R.storyboard.main()
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    /// `UIStoryboard(name: "Main", bundle: ...)`
    static func main(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.main)
    }
    
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    try storyboard.validate()
  }
  
  struct nib {
    struct _AddressViewCell: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "AddressViewCell"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> AddressViewCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? AddressViewCell
      }
      
      fileprivate init() {}
    }
    
    struct _ItemViewCell: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "ItemViewCell"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> ItemViewCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? ItemViewCell
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      try launchScreen.validate()
      try main.validate()
    }
    
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      static func validate() throws {
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    struct main: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UINavigationController
      
      let bundle = R.hostingBundle
      let listOfPerson = StoryboardViewControllerResource<ListController>(identifier: "ListOfPerson")
      let listOfPersonNav = StoryboardViewControllerResource<UIKit.UINavigationController>(identifier: "ListOfPersonNav")
      let name = "Main"
      let newPerson = StoryboardViewControllerResource<AddPersonController>(identifier: "NewPerson")
      
      func listOfPerson(_: Void = ()) -> ListController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: listOfPerson)
      }
      
      func listOfPersonNav(_: Void = ()) -> UIKit.UINavigationController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: listOfPersonNav)
      }
      
      func newPerson(_: Void = ()) -> AddPersonController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: newPerson)
      }
      
      static func validate() throws {
        if #available(iOS 11.0, *) {
        }
        if _R.storyboard.main().listOfPerson() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'listOfPerson' could not be loaded from storyboard 'Main' as 'ListController'.") }
        if _R.storyboard.main().listOfPersonNav() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'listOfPersonNav' could not be loaded from storyboard 'Main' as 'UIKit.UINavigationController'.") }
        if _R.storyboard.main().newPerson() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'newPerson' could not be loaded from storyboard 'Main' as 'AddPersonController'.") }
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
